"""
NLU parser for natural-language trading strategy descriptions.

Parses free-form strategy descriptions (Chinese or English) into structured
``StrategyIntent`` objects using OpenAI function calling.  This module is the
first stage of the strategy generation pipeline:

    user describes strategy → **strategy_nlu.parse_strategy()** → code_generator

Typical usage::

    intent = parse_strategy("當RSI低於30時買入，設2%止損，止盈5%")
    print(intent.strategy_type)       # "mean_reversion"
    print(intent.entry_signals[0])    # SignalCondition(indicator='RSI', ...)
    print(intent.risk_rules[0])       # RiskRule(rule_type='stop_loss', ...)
"""

from __future__ import annotations

import json
import logging
from enum import Enum
from typing import Any, Dict, List, Optional

from openai import OpenAI
from pydantic import BaseModel, Field, field_validator

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class TradeAction(str, Enum):
    """Supported trade actions."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    ADD = "ADD"
    REDUCE = "REDUCE"


class SignalCondition(BaseModel):
    """A single indicator-based signal condition.

    Represents conditions like ``'RSI < 30'`` or ``'MA(20) crossover MA(60)'``.

    Attributes:
        indicator: Technical indicator name, e.g. ``'RSI'``, ``'MA'``,
            ``'BOLL.lower'``.
        comparison: Comparison operator, e.g. ``'<'``, ``'>'``, ``'crossover'``.
        value: Numeric threshold value.
        params: Additional parameters such as indicator period,
            e.g. ``{'period': 14}``.
    """

    indicator: str = Field(
        ...,
        description=(
            "技術指標名稱，例如 'RSI', 'MA', 'EMA', 'MACD', 'BOLL.upper', "
            "'BOLL.lower', 'VOLUME', 'close', 'KD.K'"
        ),
    )
    comparison: str = Field(
        ...,
        description=(
            "比較運算子: '<', '>', '<=', '>=', '==', 'crossover'（向上穿越/黃金交叉）, "
            "'crossunder'（向下穿越/死亡交叉）"
        ),
    )
    value: float = Field(
        ...,
        description=(
            "閾值數值。例如 RSI < 30 中的 30，止損 2% 中的 0.02"
        ),
    )
    params: Dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "額外參數，例如指標週期 {period: 14}、MACD 快慢線 {fast: 12, slow: 26, signal: 9}"
        ),
    )

    @field_validator("indicator")
    @classmethod
    def validate_indicator(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("indicator must be a non-empty string")
        return v.strip()

    @field_validator("comparison")
    @classmethod
    def validate_comparison(cls, v: str) -> str:
        allowed = {"<", ">", "<=", ">=", "==", "crossover", "crossunder"}
        v = v.strip()
        if v not in allowed:
            raise ValueError(f"comparison must be one of {allowed}, got '{v}'")
        return v


class RiskRule(BaseModel):
    """A risk management rule.

    Attributes:
        rule_type: One of ``'stop_loss'``, ``'take_profit'``,
            ``'trailing_stop'``, ``'position_size'``.
        value: Numeric value for the rule (e.g. 0.02 for 2% stop loss).
        params: Additional parameters, e.g. ``{'method': 'percent'}``
            or ``{'reference': 'entry_price'}``.
    """

    rule_type: str = Field(
        ...,
        description=(
            "風險規則類型: stop_loss（止損）, take_profit（止盈）, "
            "trailing_stop（移動止損）, position_size（倉位大小）"
        ),
    )
    value: float = Field(
        ...,
        description=(
            "規則數值。例如止損 2% → 0.02，止盈 10% → 0.10，"
            "倉位 30% → 0.30"
        ),
    )
    params: Dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "額外參數。例如 {method: 'percent', reference: 'entry_price'}"
        ),
    )

    @field_validator("rule_type")
    @classmethod
    def validate_rule_type(cls, v: str) -> str:
        allowed = {"stop_loss", "take_profit", "trailing_stop", "position_size"}
        v = v.strip()
        if v not in allowed:
            raise ValueError(f"rule_type must be one of {allowed}, got '{v}'")
        return v


class StrategyIntent(BaseModel):
    """Structured strategy intent parsed from natural language.

    This is the primary output of the NLU stage.  It feeds directly into the
    code generator to produce executable trading strategy code.

    Attributes:
        name: Human-readable strategy name generated by the LLM.
        strategy_type: High-level strategy category.
        entry_signals: Conditions that trigger buying or adding positions.
        exit_signals: Conditions that trigger selling or reducing positions.
        risk_rules: Risk management rules (stop loss, take profit, etc.).
        position_sizing: Position sizing method description.
        time_frame: Trading time frame, e.g. ``'daily'``, ``'5min'``.
        description: Brief natural-language summary of the strategy.
    """

    name: str = Field(
        ...,
        description=(
            "策略名稱，簡短描述性名稱，例如 'RSI均值回歸策略'、'MACD趨勢跟蹤'"
        ),
    )
    strategy_type: str = Field(
        ...,
        description=(
            "策略類型: momentum（動量）, mean_reversion（均值回歸）, "
            "breakout（突破）, trend_following（趨勢跟蹤）, multi_factor（多因子）"
        ),
    )
    entry_signals: List[SignalCondition] = Field(
        default_factory=list,
        description="進場信號條件列表（買入/加倉觸發條件）",
    )
    exit_signals: List[SignalCondition] = Field(
        default_factory=list,
        description="出場信號條件列表（賣出/減倉觸發條件）",
    )
    risk_rules: List[RiskRule] = Field(
        default_factory=list,
        description="風險管理規則列表（止損、止盈、移動止損、倉位大小）",
    )
    position_sizing: str = Field(
        default="percent",
        description=(
            "倉位管理方式描述，例如 'fixed', 'percent', 'kelly', "
            "'固定100股', '資金30%'"
        ),
    )
    time_frame: str = Field(
        default="daily",
        description=(
            "交易時間框架: 'daily'（日線）, 'weekly'（週線）, 'monthly'（月線）, "
            "'5min', '15min', '60min' 等"
        ),
    )
    description: str = Field(
        default="",
        description="策略的自然語言摘要描述",
    )

    @field_validator("strategy_type")
    @classmethod
    def validate_strategy_type(cls, v: str) -> str:
        allowed = {
            "momentum",
            "mean_reversion",
            "breakout",
            "trend_following",
            "multi_factor",
        }
        v = v.strip()
        if v not in allowed:
            raise ValueError(f"strategy_type must be one of {allowed}, got '{v}'")
        return v

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("name must be a non-empty string")
        return v.strip()


# ---------------------------------------------------------------------------
# OpenAI function-calling schema
# ---------------------------------------------------------------------------

_FUNCTION_SCHEMA: Dict[str, Any] = {
    "name": "parse_strategy_intent",
    "description": (
        "將自然語言交易策略描述解析為結構化的策略意圖，"
        "包括策略類型、進出場信號、風險管理規則等。"
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "description": (
                    "策略名稱，簡短描述性名稱，"
                    "例如 'RSI均值回歸策略'、'MACD趨勢跟蹤'、"
                    "'布林通道突破策略'"
                ),
            },
            "strategy_type": {
                "type": "string",
                "enum": [
                    "momentum",
                    "mean_reversion",
                    "breakout",
                    "trend_following",
                    "multi_factor",
                ],
                "description": (
                    "策略類型: "
                    "momentum（動量策略 - 追強殺弱）, "
                    "mean_reversion（均值回歸 - 高拋低吸）, "
                    "breakout（突破策略 - 突破關鍵位入場）, "
                    "trend_following（趨勢跟蹤 - 順勢而為）, "
                    "multi_factor（多因子 - 綜合多個指標判斷）"
                ),
            },
            "entry_signals": {
                "type": "array",
                "description": "進場信號條件列表（買入/加倉觸發條件）",
                "items": {
                    "type": "object",
                    "properties": {
                        "indicator": {
                            "type": "string",
                            "description": (
                                "技術指標名稱，例如 'RSI', 'MA', 'EMA', "
                                "'MACD', 'BOLL.lower', 'VOLUME', 'close', 'KD.K'"
                            ),
                        },
                        "comparison": {
                            "type": "string",
                            "enum": [
                                "<", ">", "<=", ">=", "==",
                                "crossover", "crossunder",
                            ],
                            "description": (
                                "比較運算子: <, >, <=, >=, ==, "
                                "crossover（向上穿越/黃金交叉）, "
                                "crossunder（向下穿越/死亡交叉）"
                            ),
                        },
                        "value": {
                            "type": "number",
                            "description": (
                                "閾值數值。RSI<30 → 30，MA(20) → 20，"
                                "BOLL.lower → lower band值"
                            ),
                        },
                        "params": {
                            "type": "object",
                            "description": (
                                "額外參數。"
                                "指標週期: {period: 14}，"
                                "MACD: {fast: 12, slow: 26, signal: 9}，"
                                "布林: {period: 20, std_dev: 2}"
                            ),
                            "additionalProperties": True,
                        },
                    },
                    "required": ["indicator", "comparison", "value"],
                },
            },
            "exit_signals": {
                "type": "array",
                "description": "出場信號條件列表（賣出/減倉觸發條件）",
                "items": {
                    "type": "object",
                    "properties": {
                        "indicator": {
                            "type": "string",
                            "description": "技術指標名稱",
                        },
                        "comparison": {
                            "type": "string",
                            "enum": [
                                "<", ">", "<=", ">=", "==",
                                "crossover", "crossunder",
                            ],
                            "description": "比較運算子",
                        },
                        "value": {
                            "type": "number",
                            "description": "閾值數值",
                        },
                        "params": {
                            "type": "object",
                            "description": "額外參數",
                            "additionalProperties": True,
                        },
                    },
                    "required": ["indicator", "comparison", "value"],
                },
            },
            "risk_rules": {
                "type": "array",
                "description": (
                    "風險管理規則列表，包括止損、止盈、移動止損、倉位大小等。"
                ),
                "items": {
                    "type": "object",
                    "properties": {
                        "rule_type": {
                            "type": "string",
                            "enum": [
                                "stop_loss",
                                "take_profit",
                                "trailing_stop",
                                "position_size",
                            ],
                            "description": (
                                "風險規則類型: "
                                "stop_loss（止損）, take_profit（止盈）, "
                                "trailing_stop（移動止損）, position_size（倉位大小）"
                            ),
                        },
                        "value": {
                            "type": "number",
                            "description": (
                                "規則數值。止損 2% → 0.02，止盈 10% → 0.10，"
                                "倉位 30% → 0.30"
                            ),
                        },
                        "params": {
                            "type": "object",
                            "description": (
                                "額外參數。"
                                "例如 {method: 'percent', reference: 'entry_price'}"
                            ),
                            "additionalProperties": True,
                        },
                    },
                    "required": ["rule_type", "value"],
                },
            },
            "position_sizing": {
                "type": "string",
                "description": (
                    "倉位管理方式: "
                    "'fixed'（固定金額/股數）, "
                    "'percent'（資金百分比）, "
                    "'kelly'（凱利公式）, "
                    "或自然語言描述如 '固定100股', '資金30%'"
                ),
                "default": "percent",
            },
            "time_frame": {
                "type": "string",
                "description": (
                    "交易時間框架: 'daily'（日線）, 'weekly'（週線）, "
                    "'monthly'（月線）, '5min', '15min', '60min' 等"
                ),
                "default": "daily",
            },
            "description": {
                "type": "string",
                "description": "策略的自然語言摘要描述",
            },
        },
        "required": [
            "name",
            "strategy_type",
            "entry_signals",
            "exit_signals",
            "risk_rules",
        ],
    },
}

# ---------------------------------------------------------------------------
# System prompt with detailed instructions and few-shot examples
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """\
你是一個專業的量化交易策略分析師，專門將自然語言策略描述解析為結構化的策略意圖。
你支援中文（繁體/簡體）和英文輸入。你的輸出將直接用於自動生成交易策略代碼。

## 策略類型分類規則

### 1. momentum（動量策略）
追蹤價格動量方向，追強殺弱。
關鍵詞: 突破新高、連續上漲、動量強、成交量放大、相對強弱
### 2. mean_reversion（均值回歸）
在超買/超賣時反向操作，相信價格會回歸均值。
關鍵詞: RSI超買超賣、布林通道、均值回歸、反轉
### 3. breakout（突破策略）
突破關鍵支撐/阻力位時入場。
關鍵詞: 突破、支撐位、阻力位、區間震盪、盤整
### 4. trend_following（趨勢跟蹤）
順應中長期趨勢方向操作。
關鍵詞: 均線交叉、MACD、趨勢線、黃金交叉、死亡交叉、順勢
### 5. multi_factor（多因子）
綜合多個不同類型的指標進行決策。
關鍵詞: 同時滿足多個條件、綜合判斷、多重確認

## 信號條件解析規則

### entry_signals（進場信號）
識別所有買入/加倉的觸發條件。每個條件包含:
- indicator: 技術指標名稱（標準英文縮寫）
  常見指標: RSI, MA, EMA, MACD, BOLL, KD, VOLUME, ATR, CCI, close, open, high, low
  中文映射: 均線→MA, 布林通道→BOLL, 成交量→VOLUME, 隨機指標→KD
- comparison: 比較運算子
  中文映射: 低於/小於→<, 高於/大於→>, 突破/上穿/黃金交叉→crossover, 跌破/下穿/死亡交叉→crossunder
- value: 閾值數值（float）
- params: 指標參數（dict），如 {period: 14}

### exit_signals（出場信號）
識別所有賣出/減倉的觸發條件，格式同上。

### risk_rules（風險規則）
識別止損、止盈、移動止損、倉位大小等風險管理規則:
- stop_loss: 止損（「設2%止損」→ value=0.02）
- take_profit: 止盈（「止盈10%」→ value=0.10）
- trailing_stop: 移動止損（「移動止損3%」→ value=0.03）
- position_size: 倉位大小（「每次投入30%」→ value=0.30）
所有百分比值轉換為小數表示（2% → 0.02）。

## 中文交易語言速查表

| 中文表達 | 解析結果 |
|---------|---------|
| 當RSI低於30時買入 | entry: RSI < 30 |
| RSI高於70時賣出 | exit: RSI > 70 |
| MACD黃金交叉買入 | entry: MACD crossover signal |
| 跌破20日均線就賣 | exit: MA(20) crossunder close |
| 突破前高買入 | entry: close crossover prev_high |
| 布林通道下軌買入 | entry: close < BOLL.lower |
| 設2%止損 | risk: stop_loss=0.02 |
| 止盈5% | risk: take_profit=0.05 |
| 移動止損3% | risk: trailing_stop=0.03 |
| 分批建倉 | 多個entry_signals + position_size |
| 跌破支撐位就止損 | exit: close crossunder support_level |

## Few-shot 示例

### 示例 1: RSI均值回歸策略
輸入: "當RSI低於30時買入，RSI高於70時賣出，設2%止損，止盈5%"
輸出:
{
  "name": "RSI均值回歸策略",
  "strategy_type": "mean_reversion",
  "entry_signals": [
    {"indicator": "RSI", "comparison": "<", "value": 30.0, "params": {"period": 14}}
  ],
  "exit_signals": [
    {"indicator": "RSI", "comparison": ">", "value": 70.0, "params": {"period": 14}}
  ],
  "risk_rules": [
    {"rule_type": "stop_loss", "value": 0.02, "params": {"method": "percent"}},
    {"rule_type": "take_profit", "value": 0.05, "params": {"method": "percent"}}
  ],
  "position_sizing": "percent",
  "time_frame": "daily",
  "description": "基於RSI超買超賣的均值回歸策略，在RSI極值時反向操作"
}

### 示例 2: MACD趨勢跟蹤策略
輸入: "MACD黃金交叉買入，死亡交叉賣出，設3%止損"
輸出:
{
  "name": "MACD趨勢跟蹤策略",
  "strategy_type": "trend_following",
  "entry_signals": [
    {"indicator": "MACD", "comparison": "crossover", "value": 0.0, "params": {"fast": 12, "slow": 26, "signal": 9}}
  ],
  "exit_signals": [
    {"indicator": "MACD", "comparison": "crossunder", "value": 0.0, "params": {"fast": 12, "slow": 26, "signal": 9}}
  ],
  "risk_rules": [
    {"rule_type": "stop_loss", "value": 0.03, "params": {"method": "percent"}}
  ],
  "position_sizing": "percent",
  "time_frame": "daily",
  "description": "基於MACD交叉信號的趨勢跟蹤策略"
}

### 示例 3: 布林通道突破策略
輸入: "股價突破布林通道上軌買入，跌破下軌賣出，用資金30%建倉"
輸出:
{
  "name": "布林通道突破策略",
  "strategy_type": "breakout",
  "entry_signals": [
    {"indicator": "close", "comparison": "crossover", "value": 0.0, "params": {"reference": "BOLL.upper", "period": 20, "std_dev": 2}}
  ],
  "exit_signals": [
    {"indicator": "close", "comparison": "crossunder", "value": 0.0, "params": {"reference": "BOLL.lower", "period": 20, "std_dev": 2}}
  ],
  "risk_rules": [
    {"rule_type": "position_size", "value": 0.30, "params": {"method": "percent"}}
  ],
  "position_sizing": "percent",
  "time_frame": "daily",
  "description": "基於布林通道突破的交易策略，突破上軌做多，跌破下軌止損"
}

### 示例 4: 均線多因子策略
輸入: "20日均線向上穿越60日均線時買入，RSI確認不過熱（低於60），跌破60日均線止損"
輸出:
{
  "name": "均線交叉+RSI確認多因子策略",
  "strategy_type": "multi_factor",
  "entry_signals": [
    {"indicator": "MA", "comparison": "crossover", "value": 60.0, "params": {"period": 20, "cross_with": "MA(60)"}},
    {"indicator": "RSI", "comparison": "<", "value": 60.0, "params": {"period": 14}}
  ],
  "exit_signals": [],
  "risk_rules": [
    {"rule_type": "stop_loss", "value": 0.0, "params": {"method": "indicator", "indicator": "MA", "period": 60}}
  ],
  "position_sizing": "percent",
  "time_frame": "daily",
  "description": "均線黃金交叉進場，RSI確認動量不過熱，跌破長期均線止損"
}

### 示例 5: 英文動量策略
輸入: "Buy when price breaks 20-day high with volume spike, sell when it drops below 10-day MA, 2% trailing stop"
輸出:
{
  "name": "Breakout Momentum Strategy",
  "strategy_type": "momentum",
  "entry_signals": [
    {"indicator": "close", "comparison": "crossover", "value": 0.0, "params": {"reference": "20-day high"}},
    {"indicator": "VOLUME", "comparison": ">", "value": 0.0, "params": {"reference": "average_volume", "multiplier": 1.5}}
  ],
  "exit_signals": [
    {"indicator": "close", "comparison": "crossunder", "value": 0.0, "params": {"reference": "MA", "period": 10}}
  ],
  "risk_rules": [
    {"rule_type": "trailing_stop", "value": 0.02, "params": {"method": "percent"}}
  ],
  "position_sizing": "percent",
  "time_frame": "daily",
  "description": "動量突破策略，突破新高且放量時入場，跌破均線出場"
}

## 輸出要求
- 只輸出 function call，不要自行回答問題
- 所有百分比數值轉為小數（2% → 0.02, 10% → 0.10）
- entry_signals 和 exit_signals 至少各有一個（如果策略描述中有的話）
- risk_rules 中如果沒有明確提到，可以不填
- position_sizing 預設為 'percent'
- time_frame 預設為 'daily'
- description 用簡短的自然語言描述策略核心邏輯
- name 要簡潔且能反映策略特點
"""


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------


def get_system_prompt() -> str:
    """Return the system prompt used for strategy NLU parsing.

    Useful for debugging, logging, or displaying the prompt in a UI.

    Returns:
        The full system prompt string.
    """
    return _SYSTEM_PROMPT


# ---------------------------------------------------------------------------
# Core parsing function
# ---------------------------------------------------------------------------


def parse_strategy(
    user_input: str,
    model: str = "gpt-4o-mini",
) -> StrategyIntent:
    """Parse a natural-language strategy description into structured intent.

    Uses OpenAI function calling to extract a structured ``StrategyIntent``
    from free-form text.  Supports both Chinese (traditional/simplified) and
    English inputs.

    Args:
        user_input: Free-form text describing a trading strategy, e.g.
            ``"當RSI低於30時買入，設2%止損，止盈5%"``.
        model: OpenAI model to use (default ``"gpt-4o-mini"``).

    Returns:
        A validated :class:`StrategyIntent` instance.

    Raises:
        ValueError: If the input is empty or the LLM response cannot be
            parsed or validated.
        RuntimeError: If the OpenAI API call fails.

    Examples:
        >>> intent = parse_strategy("RSI低於30買入，高於70賣出，2%止損")
        >>> intent.strategy_type
        'mean_reversion'
        >>> intent.risk_rules[0].rule_type
        'stop_loss'
    """
    # 輸入驗證
    if not user_input or not user_input.strip():
        raise ValueError("user_input must be a non-empty string")

    client = OpenAI()  # 透過環境變數 OPENAI_API_KEY 讀取金鑰

    # 呼叫 OpenAI function calling
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user_input.strip()},
            ],
            tools=[{"type": "function", "function": _FUNCTION_SCHEMA}],
            tool_choice={
                "type": "function",
                "function": {"name": "parse_strategy_intent"},
            },
            temperature=0.0,  # 確保穩定輸出
        )
    except Exception as exc:
        logger.error("OpenAI API 呼叫失敗: %s", exc)
        raise RuntimeError(f"OpenAI API call failed: {exc}") from exc

    # 解析 function call 回應
    choice = response.choices[0]
    message = choice.message

    # 確認 LLM 有回傳 tool_calls
    if not message.tool_calls:
        raise ValueError(
            "LLM did not return a tool call. "
            f"Finish reason: {choice.finish_reason}. "
            f"Content: {message.content!r}"
        )

    tool_call = message.tool_calls[0]
    try:
        raw_args: Dict[str, Any] = json.loads(tool_call.function.arguments)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Failed to parse LLM function arguments as JSON: {exc}"
        ) from exc

    logger.debug(
        "LLM 策略解析結果: %s", json.dumps(raw_args, ensure_ascii=False)
    )

    # 使用 Pydantic 驗證並建構 StrategyIntent
    try:
        intent = StrategyIntent.model_validate(raw_args)
    except Exception as exc:
        raise ValueError(
            f"LLM output failed Pydantic validation: {exc}"
        ) from exc

    return intent


# ---------------------------------------------------------------------------
# Convenience: module-level demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # 快速測試（需設定 OPENAI_API_KEY 環境變數）
    sample_strategies = [
        "當RSI低於30時買入，RSI高於70時賣出，設2%止損，止盈5%",
        "MACD黃金交叉買入，死亡交叉賣出，設3%止損",
        "股價突破布林通道上軌買入，跌破下軌賣出，用資金30%建倉",
        "20日均線向上穿越60日均線時買入，RSI確認不過熱，跌破60日均線止損",
        "跌破支撐位就止損，突破前高就加倉，移動止損3%",
        "Buy when EMA20 crosses above EMA50, sell when price drops below MA(20), 5% stop loss",
        "Buy when RSI < 30 and volume > 2x average, 2% trailing stop",
    ]
    for desc in sample_strategies:
        print(f"\n{'='*60}")
        print(f"Strategy: {desc}")
        try:
            result = parse_strategy(desc)
            print(result.model_dump_json(indent=2))
        except Exception as e:
            print(f"Error: {e}")
